import { CHECKS, PLAN_REVISION, availableContests, comparisonCard, escapeHtml, safeHttps } from '../assets/participation-core.mjs';

export function participationCopy(lang) {
  return lang === 'zh' ? { title: '参赛准备工具', description: '核对参赛资格、估算工作时间，保存并下载自己的提交准备清单。' } : { title: 'Participation planner', description: 'Check requirements, estimate available work time, and save or download a personal submission checklist.' };
}
export function participationBody(records, lang, today, safeJson) {
  const zh = lang === 'zh', active = availableContests(records, today), first = active[0];
  const options = active.map(r => `<option value="${escapeHtml(r.id)}">${escapeHtml((zh ? r : r.en).title)} · ${r.deadline}</option>`).join('');
  return `<p class="reading-intro">${zh ? '把一个看起来不错的机会，变成一份能执行的计划。先打开规则确认资格，再估算你能投入的时间，最后留下材料和提交凭据。无需注册，也不需要调用 AI。' : 'Turn an interesting opportunity into a usable plan. Open its rules, check your requirements, estimate your available time, and record delivery evidence. No account or AI service is needed.'}</p>
    <p class="editorial-note">${zh ? '目录日期不等于精确截止时刻。下方按日估算不计入截止当天；注册、提交和答辩需分别核对。勾选表示你已自行确认，不代表主办方批准资格。' : 'A listed date is not an exact cutoff. Capacity estimates exclude the deadline day. Check registration, submission and presentation separately. A checkbox records your own confirmation, not organizer approval.'}</p>
    <form id="planner-form" class="planner-form" hidden>
      <label class="planner-select" for="plan-contest">${zh ? '选择一个待准备的机会' : 'Choose an opportunity'}<select id="plan-contest" name="contest">${options || `<option value="">${zh ? '目前没有未过期的机会' : 'No current opportunities'}</option>`}</select></label>
      <div id="plan-opportunity">${first ? comparisonCard(first, lang, today) : ''}</div>
      <fieldset class="planner-budget"><legend>${zh ? '我的时间预算' : 'My time budget'}</legend><div class="planner-inputs">
        <label for="plan-hours">${zh ? '每天能投入（小时）' : 'Available hours/day'}<input id="plan-hours" name="hours" type="number" min="0.25" max="24" step="0.25" value="2" required></label>
        <label for="plan-effort">${zh ? '预计总工作量（小时）' : 'Estimated work (hours)'}<input id="plan-effort" name="effort" type="number" min="0.25" max="10000" step="0.25" value="12" required></label>
        <label for="plan-buffer">${zh ? '个人缓冲（天）' : 'Personal buffer (days)'}<input id="plan-buffer" name="buffer" type="number" min="0" max="30" step="1" value="2" required></label>
      </div><p class="planner-help">${zh ? '总工作量由你估计，包含制作、测试、授权整理和提交。工具假设每天都能投入所填小时，不自动扣除休息日或等待发布审核的时间。' : 'Include production, tests, rights checks and submission in your estimate. The tool assumes the same hours every day; days off and publication review delays are not deducted automatically.'}</p><p id="plan-summary" class="plan-summary" aria-live="polite"></p></fieldset>
      <fieldset class="planner-checks"><legend>${zh ? '开工与提交前，逐项核对' : 'Check before starting and submitting'}</legend><p id="plan-progress" class="planner-help" aria-live="polite"></p>${CHECKS.map(c => `<label for="plan-${c.id}"><input id="plan-${c.id}" name="${c.id}" type="checkbox"><span>${c[lang]}</span></label>`).join('')}</fieldset>
      <label class="planner-notes" for="plan-notes">${zh ? '我的依据与待确认事项' : 'My evidence and open questions'}<textarea id="plan-notes" name="notes" rows="5" maxlength="4000" placeholder="${zh ? '例如：规则链接与段落、注册是否完成、缺少的授权、个人完成日期。不要填写证件或账号密码。' : 'For example: rule URL and section, registration status, missing permissions and a personal target. Do not enter identity documents or credentials.'}"></textarea></label>
      <div id="plan-print-notes" class="planner-print-notes"></div><p id="plan-save-status" class="planner-help" role="status">${zh ? '填写内容只保存在此浏览器；可下载备份。' : 'Entries stay in this browser; download a backup if needed.'}</p>
      <div class="planner-actions"><button class="button button-primary" id="plan-download" type="button">${zh ? '下载 Markdown 清单' : 'Download Markdown checklist'}</button><button class="button button-secondary" id="plan-print" type="button">${zh ? '打印 / 保存 PDF' : 'Print / save PDF'}</button><button class="button button-secondary" id="plan-reset" type="button">${zh ? '清空当前计划' : 'Clear this plan'}</button></div>
    </form>
    <noscript><p class="editorial-note">${zh ? '交互预算、勾选和保存需要 JavaScript。下面的方法与来源无需脚本也能阅读。' : 'Budgeting, checkboxes and saving require JavaScript. The method and sources below remain readable without scripts.'}</p></noscript>
    <section><h2>${zh ? '怎样用好这份计划' : 'How to use the plan'}</h2><ol class="planner-method"><li><strong>${zh ? '先处理不能靠加班解决的问题。' : 'Resolve constraints before estimating effort.'}</strong> ${zh ? '地区、年龄、团队人数、作品形式或版权不符合要求，增加制作时间也不能弥补。把未知项写下来，带着具体规则向主办方确认。' : 'Region, age, team size, deliverable type and rights cannot be fixed by working longer. Write down unknowns and ask the organizer about the relevant rule.'}</li><li><strong>${zh ? '工作量来自任务拆分。' : 'Estimate from tasks.'}</strong> ${zh ? '不要只估生成图片或写代码的时间。把构思、制作、测试、材料和上传拆开相加。12 小时只是表单初始示例，不是工具对任何赛事的评估。' : 'Count concept, production, testing, materials and upload separately. The initial 12 hours is an example input, not an assessment of any contest.'}</li><li><strong>${zh ? '把缓冲当成自己的安排。' : 'Keep buffer time personal.'}</strong> ${zh ? '两天是工具的示例起点，不是普遍足够的标准。跨时区、需要上线或等待授权的作品，可能需要更多时间；请自己调整。' : 'Two days is a starting example, not a universally sufficient buffer. Cross-zone entries, publication and rights clearance may need longer.'}</li><li><strong>${zh ? '保存可证明的完成状态。' : 'Keep completion evidence.'}</strong> ${zh ? '注册确认邮件、提交回执、可访问的作品链接与最终文件版本，比一句“应该交上了”更可靠。此工具不上传文件、不替你报名，也不检查官方系统是否收件。' : 'Keep registration confirmation, a submission receipt, an accessible demo and the final file version. The tool does not upload, register or verify receipt in an organizer system.'}</li></ol></section>
    <section><h2>${zh ? '从真实例子理解准备工作' : 'Learn from concrete examples'}</h2><ul><li><a href="${zh ? '' : '/en'}/guides/browser-game-and-mini-program-entry/">${zh ? '网页小游戏与小程序参赛交付，有什么不同？' : 'Browser games and mini-program deliverables'}</a></li><li><a href="${zh ? '' : '/en'}/guides/registration-versus-submission-deadlines/">${zh ? '为什么注册和提交需要两个提醒？' : 'Why registration and submission need separate reminders'}</a></li></ul></section>
    <section><h2>${zh ? '数据、隐私与限制' : 'Data, privacy and limits'}</h2><p>${zh ? '机会来自同一份自动同步目录。核验日期保留源记录原值，不会因打开工具而变新。提交日期已过的记录不再作为新的选项；如果源数据删除了机会，旧计划可能无法再次打开，请下载备份。' : 'Opportunities use the automatically synced directory. Verification dates retain their source values. Past dates are excluded from new choices. A removed source record may make an old plan inaccessible; download a backup.'}</p><p>${zh ? '各机会的计划分别保存在 localStorage，清空当前计划不影响其他机会。清除浏览器数据会清除全部本地计划。工具不会将备注发给本站服务器或模型服务；托管请求的数据处理见' : 'Plans use localStorage, separately for each opportunity. Clearing one does not clear others. Clearing browser data removes all local plans. Notes are not sent to our server or a model service; hosting-request practices are described in our'} <a href="${zh ? '' : '/en'}/privacy/">${zh ? '隐私说明' : 'privacy notice'}</a>${zh ? '。' : '.'}</p></section>
    <details class="planner-source-list"><summary>${zh ? '本次发布的机会与官方来源' : 'Published opportunities and official sources'}</summary><ul>${active.map(r => `<li><a href="${safeHttps(r.rules_url)}" target="_blank" rel="noopener noreferrer">${escapeHtml((zh ? r : r.en).title)}</a> · ${r.deadline} · ${zh ? '来源核验' : 'Source verified'} ${r.verified_on}</li>`).join('')}</ul></details>
    <script type="application/json" id="planner-data">${safeJson({ records: active, lang, revision: PLAN_REVISION })}</script><script type="module" src="/assets/participation.js"></script>`;
}
